name: deploy angry-king
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - name: Install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.20.2"
      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm dependencies
        with:
          version: 8.8.0
          run_install: true
      - name: Run build task
        run: pnpm build
      - name: Deploy to tencent cloud server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: ${{vars.ARGS}}
          SOURCE: "dist/"
          REMOTE_HOST: "62.234.163.223"
          REMOTE_USER: ${{vars.REMOTE_USER}}
          TARGET: ${{ vars.TARGET}}
      - name: Deploy to aliyun cloud server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: ${{vars.ARGS}}
          SOURCE: "dist/"
          REMOTE_HOST: "182.92.222.231"
          REMOTE_USER: ${{vars.REMOTE_USER}}
          TARGET: ${{ vars.TARGET}}
